const PUBLIC_LABEL_MAP: Record<string, string> = {
  Agent: '智能体',
  App: '应用',
  API: '接口',
  Browser: '浏览器',
  CLI: '命令行',
  IDE: '开发工作台',
  Coze: '扣子',
  Dashboard: '看板',
  Docs: '文档',
  Frontend: '前端',
  Backend: '后端',
  Guide: '指南',
  Library: '藏馆',
  Markdown: '资料页',
  PWA: '可安装网页',
  Path: '路线',
  Prompt: '提示词',
  Resource: '资料',
  Security: '隐私',
  Timeline: '年谱',
  Work: '工坊',
  Workflow: '工作流',
  X: '未知',
  agent: '智能体',
  'agent-builder': '智能体搭建器',
  'agent workflow': '智能体工作流',
  'archive-derived': '旧资料脱敏整理',
  archive: '资料整理',
  backend: '后端',
  'beginner-friendly': '新手友好',
  cognition: '认知变化',
  code: '代码',
  coze: '扣子',
  curated: '精选整理',
  'desktop-app': '桌面应用',
  frontend: '前端',
  governance: '治理',
  guide: '指南',
  'github references': 'GitHub 参考',
  'github-skills': 'GitHub 技能',
  'learning design': '学习设计',
  'lifecycle package': '复刻学习包',
  'local compile': '资料整理',
  'local model workflow': '本地模型工作流',
  llm: '大模型',
  'llm-wiki': '大模型资料库',
  'official docs': '官方文档',
  'official pattern': '官方模式',
  path: '路线',
  project: '项目',
  publication: '发布',
  'public project': '公开项目',
  'public wiki': '公开资料',
  'public-safe': '公开安全',
  'public-safe rewrite': '公开安全改写',
  rag: '资料检索',
  security: '边界',
  showcase: '展示',
  'site-data': '展示内容',
  skills: '技能',
  tool: '工具',
  tools: '工具',
  vibe: '氛围式编程',
  workflow: '工作流',
  xiaoan: '小安',
  'an-llm-wiki': '安的公开资料库',
};

export function toPublicLabel(label?: string | null) {
  if (!label) return '';
  const normalized = label.trim();
  return PUBLIC_LABEL_MAP[normalized] ?? normalized;
}
