// Generated by site/scripts/sync-site-data.mjs. Do not edit by hand.
import type { FeedItem, JournalEntry, LibraryItem, Path, TimelineEvent, Work } from "@/types";
import type { PathDetail } from "./mockPaths";

export const libraryItems: LibraryItem[] = [
  {
    "id": "c_32c45035f9107070",
    "title": "Agent Skill Governance",
    "description": "A public-safe model for preserving agent and skill knowledge without exposing local prompts or private runtime state.",
    "type": "article",
    "tags": [
      "agent",
      "skills",
      "governance",
      "llm-wiki",
      "curated"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-concepts-agent-skill-governance"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/local-private-compile-2026-05-13]]"
      },
      {
        "label": "来源 2",
        "url": "[[wiki/synthesis/karpathy-official-wiki-layer]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "It lets the archive preserve agent operating knowledge without publishing raw rules, prompts, or local state.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "It lets the archive preserve agent operating knowledge without publishing raw rules, prompts, or local state.",
    "isRecommended": true,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_8008030b505902e0",
    "title": "Private To Public Promotion Pipeline",
    "description": "The workflow for rewriting local-only archive material into public-safe wiki pages.",
    "type": "article",
    "tags": [
      "publication",
      "workflow",
      "llm-wiki",
      "curated"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-concepts-private-to-public-promotion-pipeline"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/karpathy-llm-wiki-pattern]]"
      },
      {
        "label": "来源 2",
        "url": "[[wiki/sources/local-private-compile-2026-05-13]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "It gives the archive a repeatable way to grow without turning private review material into public content.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "It gives the archive a repeatable way to grow without turning private review material into public content.",
    "isRecommended": true,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_151dd4949baa1108",
    "title": "Public Site Data Boundary",
    "description": "The architecture boundary that keeps the website consuming curated public JSON instead of raw Obsidian content.",
    "type": "article",
    "tags": [
      "frontend",
      "backend",
      "site-data",
      "publication",
      "curated"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-concepts-public-site-data-boundary"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/local-private-compile-2026-05-13]]"
      },
      {
        "label": "来源 2",
        "url": "[[wiki/synthesis/karpathy-official-wiki-layer]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "It prevents the future website from depending on private vault structure or unreviewed Markdown.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "It prevents the future website from depending on private vault structure or unreviewed Markdown.",
    "isRecommended": true,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_ad9a9fc54757ca67",
    "title": "Sources and Data Policy",
    "description": "Source, privacy, and publication rules for this public-safe wiki.",
    "type": "doc",
    "tags": [
      "llm-wiki",
      "sources",
      "privacy"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-sources-and-data-policy"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/karpathy-llm-wiki-pattern]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "Source, privacy, and publication rules for this public-safe wiki.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "已从公开 wiki 编译为可展示条目。",
    "isRecommended": false,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_34b380dfec2c06c0",
    "title": "GitHub Reference Projects",
    "description": "Secondary engineering references for local-first LLM Wiki implementations.",
    "type": "doc",
    "tags": [
      "llm-wiki",
      "github",
      "source"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-sources-github-reference-projects"
      },
      {
        "label": "来源 1",
        "url": "https://github.com/kytmanov/obsidian-llm-wiki-local"
      },
      {
        "label": "来源 2",
        "url": "https://github.com/shannhk/llm-wikid"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "Secondary engineering references for local-first LLM Wiki implementations.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "已从公开 wiki 编译为可展示条目。",
    "isRecommended": false,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_08b81444115464f6",
    "title": "Karpathy LLM Wiki Pattern",
    "description": "Official pattern source for this vault architecture.",
    "type": "doc",
    "tags": [
      "llm-wiki",
      "source",
      "obsidian"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-sources-karpathy-llm-wiki-pattern"
      },
      {
        "label": "来源 1",
        "url": "https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "Official pattern source for this vault architecture.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "已从公开 wiki 编译为可展示条目。",
    "isRecommended": false,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_d1f1b66d423fc694",
    "title": "llm-wikid",
    "description": "Secondary GitHub reference for Obsidian vault template and wiki maintenance conventions.",
    "type": "doc",
    "tags": [
      "llm-wiki",
      "github",
      "source"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-sources-llm-wikid"
      },
      {
        "label": "来源 1",
        "url": "https://github.com/shannhk/llm-wikid"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "Secondary GitHub reference for Obsidian vault template and wiki maintenance conventions.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "已从公开 wiki 编译为可展示条目。",
    "isRecommended": false,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_58d7fda66c48c030",
    "title": "Local Private Compile 2026-05-13",
    "description": "Public-safe source record for the local-only private compile pass that informed the next public wiki pages.",
    "type": "doc",
    "tags": [
      "llm-wiki",
      "source",
      "publication"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-sources-local-private-compile-2026-05-13"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/karpathy-llm-wiki-pattern]]"
      },
      {
        "label": "来源 2",
        "url": "[[wiki/sources/pre-rebuild-vault-archive]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "Public-safe source record for the local-only private compile pass that informed the next public wiki pages.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "已从公开 wiki 编译为可展示条目。",
    "isRecommended": false,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_55208509a7f3108b",
    "title": "obsidian-llm-wiki-local",
    "description": "Secondary GitHub reference for local-first LLM Wiki implementation ideas.",
    "type": "doc",
    "tags": [
      "llm-wiki",
      "github",
      "source"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-sources-obsidian-llm-wiki-local"
      },
      {
        "label": "来源 1",
        "url": "https://github.com/kytmanov/obsidian-llm-wiki-local"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "Secondary GitHub reference for local-first LLM Wiki implementation ideas.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "已从公开 wiki 编译为可展示条目。",
    "isRecommended": false,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_e408088da7f9f832",
    "title": "Pre-Rebuild Vault Archive",
    "description": "Local private archive used as the source for public-safe migration.",
    "type": "doc",
    "tags": [
      "llm-wiki",
      "source",
      "archive"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-sources-pre-rebuild-vault-archive"
      }
    ],
    "rating": 4,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "Local private archive used as the source for public-safe migration.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "已从公开 wiki 编译为可展示条目。",
    "isRecommended": false,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "已进入公开展示层",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_910d420ab933c045",
    "title": "Archive Information Architecture",
    "description": "The public information backbone for organizing projects, capabilities, timeline, and review queues before final showcase pages.",
    "type": "article",
    "tags": [
      "archive",
      "information-architecture",
      "synthesis",
      "curated"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-synthesis-archive-information-architecture"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/local-private-compile-2026-05-13]]"
      },
      {
        "label": "来源 2",
        "url": "[[wiki/synthesis/karpathy-official-wiki-layer]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "It makes information retrievable before it is made presentational.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "It makes information retrievable before it is made presentational.",
    "isRecommended": true,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_40e886748f617bef",
    "title": "Capability Evidence Matrix",
    "description": "Public-safe matrix linking capabilities to project evidence, repeatable workflows, and future wiki pages.",
    "type": "article",
    "tags": [
      "skills",
      "capabilities",
      "evidence",
      "curated"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-synthesis-capability-evidence-matrix"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/local-private-compile-2026-05-13]]"
      },
      {
        "label": "来源 2",
        "url": "[[wiki/topics/skills-and-tools-moc]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "It turns capability claims into evidence-backed archive structure.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "It turns capability claims into evidence-backed archive structure.",
    "isRecommended": true,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_d2558f33511a9ddd",
    "title": "Information Review Queue",
    "description": "Public-safe review queue for unresolved information decisions before more archive content is promoted.",
    "type": "article",
    "tags": [
      "review",
      "publication",
      "information-architecture",
      "curated"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-synthesis-information-review-queue"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/local-private-compile-2026-05-13]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "It makes missing or uncertain information explicit instead of hiding it behind polished pages.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "It makes missing or uncertain information explicit instead of hiding it behind polished pages.",
    "isRecommended": true,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_8a14bcb2a5e3fd90",
    "title": "Personal Archive Public Roadmap",
    "description": "A staged roadmap for growing the public personal archive from safe architecture pages into project and capability pages.",
    "type": "article",
    "tags": [
      "archive",
      "roadmap",
      "synthesis",
      "publication",
      "curated"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-synthesis-personal-archive-public-roadmap"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/local-private-compile-2026-05-13]]"
      },
      {
        "label": "来源 2",
        "url": "[[wiki/projects/personal-archive-platform]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "It turns a large local archive into a staged public writing plan instead of a risky bulk release.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "It turns a large local archive into a staged public writing plan instead of a risky bulk release.",
    "isRecommended": true,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_43043860b6d67e12",
    "title": "Project Evidence Matrix",
    "description": "Public-safe matrix of project themes, evidence strength, privacy risk, and next promotion action.",
    "type": "article",
    "tags": [
      "projects",
      "evidence",
      "synthesis",
      "curated"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-synthesis-project-evidence-matrix"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/local-private-compile-2026-05-13]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "It ranks project information by public readiness instead of turning every local trace into a showcase item.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "It ranks project information by public readiness instead of turning every local trace into a showcase item.",
    "isRecommended": true,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_4ffbf9e307e04258",
    "title": "Public Growth Timeline Framework",
    "description": "A framework for turning private timeline evidence into public milestones without exposing sensitive personal material.",
    "type": "article",
    "tags": [
      "timeline",
      "growth",
      "publication",
      "curated"
    ],
    "links": [
      {
        "label": "打开详情",
        "url": "/content/wiki-synthesis-public-growth-timeline-framework"
      },
      {
        "label": "来源 1",
        "url": "[[wiki/sources/local-private-compile-2026-05-13]]"
      }
    ],
    "rating": 5,
    "status": "done",
    "cover": "/hero-cover.jpg",
    "useCase": "It preserves growth information without publishing private memories or raw personal records.",
    "difficulty": "easy",
    "timeToLearn": "约 1 分钟",
    "myThoughts": "It preserves growth information without publishing private memories or raw personal records.",
    "isRecommended": true,
    "recommendedFor": "想理解公开资料库、AI 操作路径和复刻方法的新手",
    "pros": [
      "有来源引用",
      "章节结构清晰"
    ],
    "cons": [],
    "whoFor": "新手、协作者和未来的自己",
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  }
];

export const paths: Path[] = [
  {
    "id": "c_b335630551682c19",
    "title": "An LLM Wiki",
    "description": "A public, privacy-filtered Obsidian LLM Wiki rebuilt around Karpathy's llm-wiki pattern.",
    "cover": "/path-frontend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "An LLM Wiki",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Start Here",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Operating Model",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Current Rebuild",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "llm-wiki",
      "obsidian",
      "public"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_a48746cae70c44e7",
    "title": "An LLM Wiki Index",
    "description": "Root navigation page for the public-safe Obsidian LLM Wiki.",
    "cover": "/path-design.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "An LLM Wiki Index",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "llm-wiki",
      "index"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_0b2b8021fc47d672",
    "title": "LLM Wiki Index",
    "description": "Short workbench for the rebuilt public-safe LLM Wiki.",
    "cover": "/path-backend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "LLM Wiki Index",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Start Here",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Maps",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Source Notes",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "llm-wiki",
      "moc"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_3d19f3d825d4e136",
    "title": "AI Agent Systems MOC",
    "description": "Map for public-safe AI agent framework and architecture notes migrated into the wiki.",
    "cover": "/path-frontend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "AI Agent Systems MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Frameworks",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Architecture Notes",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Project Architecture",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "ai-agent",
      "moc",
      "systems"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_87e2a1ac5dbe8a31",
    "title": "LLM Wiki MOC",
    "description": "Map for the vault architecture, schema, source policy, and rebuild alignment notes.",
    "cover": "/path-design.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "LLM Wiki MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Architecture",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Rebuild Records",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Migrated LLM Wiki Notes",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "llm-wiki",
      "moc",
      "architecture"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_74981be21c4f4c9f",
    "title": "Personal Archive MOC",
    "description": "Map of the public personal archive platform, promotion workflow, frontend data boundary, and publication roadmap.",
    "cover": "/path-backend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "Personal Archive MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Platform",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Promotion Workflow",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Website Data",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-5",
        "title": "Agent And Skills",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 5,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "archive",
      "moc",
      "llm-wiki",
      "curated"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  },
  {
    "id": "c_7e9d08f8f6eda5d4",
    "title": "Publication Maintenance MOC",
    "description": "Map for publication gates, privacy scans, manifests, restore evidence, and root maintenance work.",
    "cover": "/path-frontend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "Publication Maintenance MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Policy",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Validation",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Manifests",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-5",
        "title": "Maintenance",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 5,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "publication",
      "maintenance",
      "privacy",
      "moc"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  },
  {
    "id": "c_68d8f2407d41eb74",
    "title": "Skills and Tools MOC",
    "description": "Map for migrated public-safe skills, tool notes, and reusable operational patterns.",
    "cover": "/path-design.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "Skills and Tools MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Skill Indexes",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Frequently Used Skills",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Tooling Areas",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "skills",
      "tools",
      "moc"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12"
  }
];

export const pathDetails: Record<string, PathDetail> = {
  "c_b335630551682c19": {
    "id": "c_b335630551682c19",
    "title": "An LLM Wiki",
    "description": "A public, privacy-filtered Obsidian LLM Wiki rebuilt around Karpathy's llm-wiki pattern.",
    "cover": "/path-frontend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "An LLM Wiki",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Start Here",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Operating Model",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Current Rebuild",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "llm-wiki",
      "obsidian",
      "public"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12",
    "longDescription": "# An LLM Wiki\n\nThis is a public-safe personal Obsidian knowledge base rebuilt around Andrej Karpathy's LLM Wiki pattern.\n\n## Start Here\n\n- [[wiki/index]] - curated wiki workbench\n- [[wiki/topics/llm-wiki-moc]] - architecture and operation map\n- [[wiki/topics/publication-maintenance-moc]] - publication and validation map\n- [[wiki/sources/karpathy-llm-wiki-pattern]] - official architecture source\n- [[wiki/sources/github-reference-projects]] - secondary implementation references\n- [Kimi frontend reference](docs/kimi-frontend-reference.md) - public-safe product brief, data model, prompt patterns, and frontend acceptance criteria\n- [Archive platform project constraints](docs/archive-platform-project-constraints.md) - frontend, backend, privacy, data, and agent operating constraints\n- [Archive content style and ingest workflow](docs/archive-content-style-and-ingest-workflow.md) - content depth, writing standard, formal data workflow, and validation gates\n- [Agent skill stack](docs/agent-skill-stack.md) - GitHub-sourced skills and task-specific skill chains for frontend, backend, app, QA, security, and release work\n- [[AGENTS]] - agent maintenance rules\n- [[CLAUDE]] - wiki schema\n- [[log]] - append-only rebuild and maintenance log\n\n## Operating Model\n\nRaw material stays local. Public pages are compiled, linked, and source-aware Markdown notes. Sensitive local paths, credentials, private memory, raw conversations, and unreviewed imports are excluded from the public repository.\n\n## Current Rebuild\n\n- Archive ID: `pre-karpathy-rebuild-20260512-143127`\n- Migrated public-safe notes: 192\n- Reviewed source files: 11147",
    "pitfalls": [],
    "advancedDirections": [
      {
        "title": "wiki/index",
        "link": "wiki/index"
      },
      {
        "title": "wiki/topics/llm-wiki-moc",
        "link": "wiki/topics/llm-wiki-moc"
      },
      {
        "title": "wiki/topics/publication-maintenance-moc",
        "link": "wiki/topics/publication-maintenance-moc"
      },
      {
        "title": "wiki/sources/karpathy-llm-wiki-pattern",
        "link": "wiki/sources/karpathy-llm-wiki-pattern"
      }
    ],
    "relatedResourceIds": []
  },
  "c_a48746cae70c44e7": {
    "id": "c_a48746cae70c44e7",
    "title": "An LLM Wiki Index",
    "description": "Root navigation page for the public-safe Obsidian LLM Wiki.",
    "cover": "/path-design.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "An LLM Wiki Index",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "llm-wiki",
      "index"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12",
    "longDescription": "# An LLM Wiki Index\n\n- [[README]] - overview\n- [[wiki/index]] - main wiki workbench\n- [[wiki/synthesis/karpathy-official-wiki-layer]] - official wiki layer contract\n- [[wiki/topics/personal-archive-moc]] - personal archive and website backend map\n- [[wiki/topics/llm-wiki-moc]] - architecture and operations\n- [[wiki/topics/ai-agent-systems-moc]] - agent systems map\n- [[wiki/topics/skills-and-tools-moc]] - skills and tooling map\n- [[wiki/topics/publication-maintenance-moc]] - publication gates and restore evidence\n- [[wiki/sources-and-data-policy]] - source and publication policy\n- [[wiki/sources/karpathy-llm-wiki-pattern]] - official architecture source\n- [raw_sources.csv](manifests/raw_sources.csv) - source registry\n- [publication_review.csv](manifests/publication_review.csv) - migration and privacy review ledger\n- [[log]] - maintenance log",
    "pitfalls": [],
    "advancedDirections": [
      {
        "title": "README",
        "link": "README"
      },
      {
        "title": "wiki/index",
        "link": "wiki/index"
      },
      {
        "title": "wiki/synthesis/karpathy-official-wiki-layer",
        "link": "wiki/synthesis/karpathy-official-wiki-layer"
      },
      {
        "title": "wiki/topics/personal-archive-moc",
        "link": "wiki/topics/personal-archive-moc"
      }
    ],
    "relatedResourceIds": []
  },
  "c_0b2b8021fc47d672": {
    "id": "c_0b2b8021fc47d672",
    "title": "LLM Wiki Index",
    "description": "Short workbench for the rebuilt public-safe LLM Wiki.",
    "cover": "/path-backend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "LLM Wiki Index",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Start Here",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Maps",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Source Notes",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "llm-wiki",
      "moc"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12",
    "longDescription": "# LLM Wiki Index\n\nThis is the short workbench for the public wiki. Raw sources and private staging stay outside the public graph.\n\n## Start Here\n\n- [[README]] - vault overview\n- [[wiki/sources/karpathy-llm-wiki-pattern]] - official architecture source\n- [[wiki/synthesis/karpathy-official-wiki-layer]] - public wiki layer contract\n- [[wiki/sources-and-data-policy]] - source and publication boundary\n- [[wiki/projects/root-maintenance-backlog]] - current maintenance backlog\n- [[log]] - append-only maintenance log\n\n## Maps\n\n- [[wiki/topics/personal-archive-moc]] - public personal archive and website data map\n- [[wiki/synthesis/archive-information-architecture]] - information backbone for projects, capabilities, timeline, and review queues\n- [[wiki/topics/llm-wiki-moc]] - LLM Wiki architecture and operations\n- [[wiki/topics/ai-agent-systems-moc]] - AI agent systems and framework notes\n- [[wiki/topics/skills-and-tools-moc]] - migrated skills and reusable tooling notes\n- [[wiki/topics/publication-maintenance-moc]] - publication checks, privacy gates, manifests, and restore records\n\n## Source Notes\n\n- [[wiki/sources/karpathy-llm-wiki-pattern]] - official pattern source\n- [[wiki/sources/local-private-compile-2026-05-13]] - public-safe source record for the current local compile pass\n- [[wiki/sources/github-reference-projects]] - secondary project index\n- [[wiki/sources/obsidian-llm-wiki-local]] - local-first reference project\n- [[wiki/sources/llm-wikid]] - vault-template reference project\n- [[wiki/sources/pre-rebuild-vault-archive]] - private migration source record",
    "pitfalls": [],
    "advancedDirections": [
      {
        "title": "README",
        "link": "README"
      },
      {
        "title": "wiki/sources/karpathy-llm-wiki-pattern",
        "link": "wiki/sources/karpathy-llm-wiki-pattern"
      },
      {
        "title": "wiki/synthesis/karpathy-official-wiki-layer",
        "link": "wiki/synthesis/karpathy-official-wiki-layer"
      },
      {
        "title": "wiki/sources-and-data-policy",
        "link": "wiki/sources-and-data-policy"
      }
    ],
    "relatedResourceIds": []
  },
  "c_3d19f3d825d4e136": {
    "id": "c_3d19f3d825d4e136",
    "title": "AI Agent Systems MOC",
    "description": "Map for public-safe AI agent framework and architecture notes migrated into the wiki.",
    "cover": "/path-frontend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "AI Agent Systems MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Frameworks",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Architecture Notes",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Project Architecture",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "ai-agent",
      "moc",
      "systems"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12",
    "longDescription": "# AI Agent Systems MOC\n\nThis map keeps the agent notes navigable without depending on old private vault paths.\n\n## Frameworks\n\n- [[wiki/topics/04-知识库-领域研究-Agent生态-Agent-生态-MOC]] - agent ecosystem overview\n- [[wiki/topics/04-知识库-领域研究-Agent生态-AutoGen]]\n- [[wiki/topics/04-知识库-领域研究-Agent生态-Browser-use]]\n- [[wiki/topics/04-知识库-领域研究-Agent生态-CrewAI]]\n- [[wiki/topics/04-知识库-领域研究-Agent生态-LangChain]]\n- [[wiki/topics/04-知识库-领域研究-Agent生态-LlamaIndex]]\n- [[wiki/topics/04-知识库-领域研究-Agent生态-MCP]]\n- [[wiki/topics/04-知识库-领域研究-Agent生态-SWE-Agent]]\n\n## Architecture Notes\n\n- [[wiki/concepts/agent-skill-governance]] - public-safe skill and rule governance\n- [[wiki/topics/04-知识库-领域研究-AI-Agent技术-架构设计-Agent_Computer_Interface_Best_Practices]]\n- [[wiki/topics/04-知识库-领域研究-AI-Agent技术-架构设计-Agent_Design_Patterns_2026]]\n- [[wiki/topics/04-知识库-领域研究-AI-Agent技术-架构设计-Agentic_Workflow_Optimization_2026]]\n- [[wiki/topics/04-知识库-领域研究-AI-Agent技术-架构设计-多Agent协调与受控委派-2026-04-11]]\n- [[wiki/topics/04-知识库-领域研究-AI-Agent技术-架构设计-多Agent通信信封与工件传递-2026-04-11]]\n\n## Project Architecture\n\n- [[wiki/projects/04-知识库-领域研究-AI-Agent技术-项目架构-an-clan_Project_Architecture]]\n- [[wiki/projects/04-知识库-领域研究-AI-Agent技术-项目架构-mcc_Project_Architecture]]\n- [[wiki/projects/04-知识库-领域研究-AI-Agent技术-项目架构-zongmen-gui_Project_Architecture]]",
    "pitfalls": [],
    "advancedDirections": [
      {
        "title": "wiki/topics/04-知识库-领域研究-Agent生态-Agent-生态-MOC",
        "link": "wiki/topics/04-知识库-领域研究-Agent生态-Agent-生态-MOC"
      },
      {
        "title": "wiki/topics/04-知识库-领域研究-Agent生态-AutoGen",
        "link": "wiki/topics/04-知识库-领域研究-Agent生态-AutoGen"
      },
      {
        "title": "wiki/topics/04-知识库-领域研究-Agent生态-Browser-use",
        "link": "wiki/topics/04-知识库-领域研究-Agent生态-Browser-use"
      },
      {
        "title": "wiki/topics/04-知识库-领域研究-Agent生态-CrewAI",
        "link": "wiki/topics/04-知识库-领域研究-Agent生态-CrewAI"
      }
    ],
    "relatedResourceIds": []
  },
  "c_87e2a1ac5dbe8a31": {
    "id": "c_87e2a1ac5dbe8a31",
    "title": "LLM Wiki MOC",
    "description": "Map for the vault architecture, schema, source policy, and rebuild alignment notes.",
    "cover": "/path-design.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "LLM Wiki MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Architecture",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Rebuild Records",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Migrated LLM Wiki Notes",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "llm-wiki",
      "moc",
      "architecture"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12",
    "longDescription": "# LLM Wiki MOC\n\nUse this page for the wiki operating model, not for raw migrated content.\n\n## Architecture\n\n- [[wiki/sources/karpathy-llm-wiki-pattern]] - official pattern source\n- [[wiki/synthesis/karpathy-official-wiki-layer]] - public wiki layer contract\n- [[CLAUDE]] - local schema and page contract\n- [[AGENTS]] - operating rules for future agents\n- [[wiki/sources-and-data-policy]] - public/private source boundary\n\n## Rebuild Records\n\n- [[wiki/projects/wiki-projects-karpathy-llm-wiki-alignment-2026-05-12]] - rebuild alignment note\n- [[wiki/projects/root-maintenance-backlog]] - durable follow-up list\n- [[wiki/sources/pre-rebuild-vault-archive]] - migration source record\n- [[log]] - append-only operation log\n\n## Migrated LLM Wiki Notes\n\n- [[wiki/topics/04-知识库-LLM-Wiki-articles-2026-04-11-Agentic-Wiki-编译样本]]\n- [[wiki/topics/04-知识库-LLM-Wiki-articles-2026-04-14-多仓接入-样例]]\n- [[wiki/topics/04-知识库-LLM-Wiki-index]]\n- [[wiki/topics/04-知识库-LLM-Wiki-log]]",
    "pitfalls": [],
    "advancedDirections": [
      {
        "title": "wiki/sources/karpathy-llm-wiki-pattern",
        "link": "wiki/sources/karpathy-llm-wiki-pattern"
      },
      {
        "title": "wiki/synthesis/karpathy-official-wiki-layer",
        "link": "wiki/synthesis/karpathy-official-wiki-layer"
      },
      {
        "title": "CLAUDE",
        "link": "CLAUDE"
      },
      {
        "title": "AGENTS",
        "link": "AGENTS"
      }
    ],
    "relatedResourceIds": []
  },
  "c_74981be21c4f4c9f": {
    "id": "c_74981be21c4f4c9f",
    "title": "Personal Archive MOC",
    "description": "Map of the public personal archive platform, promotion workflow, frontend data boundary, and publication roadmap.",
    "cover": "/path-backend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "Personal Archive MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Platform",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Promotion Workflow",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Website Data",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-5",
        "title": "Agent And Skills",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 5,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "archive",
      "moc",
      "llm-wiki",
      "curated"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13",
    "longDescription": "# Personal Archive MOC\n\nThis map is the public navigation layer for the personal archive project.\n\n## Platform\n\n- [[wiki/projects/personal-archive-platform]] - public project overview\n- [[wiki/synthesis/archive-information-architecture]] - information backbone\n- [[wiki/synthesis/personal-archive-public-roadmap]] - staged publication plan\n- [[wiki/synthesis/karpathy-official-wiki-layer]] - wiki layer contract\n\n## Promotion Workflow\n\n- [[wiki/synthesis/project-evidence-matrix]] - project evidence and readiness\n- [[wiki/synthesis/capability-evidence-matrix]] - capability evidence and repeatable workflows\n- [[wiki/synthesis/public-growth-timeline-framework]] - public timeline classification\n- [[wiki/synthesis/information-review-queue]] - unresolved information decisions\n- [[wiki/concepts/private-to-public-promotion-pipeline]] - how local-only review material becomes public pages\n- [[wiki/sources/local-private-compile-2026-05-13]] - public-safe source record for the current compile pass\n- [[wiki/sources-and-data-policy]] - source and publication boundary\n\n## Website Data\n\n- [[wiki/concepts/public-site-data-boundary]] - frontend/backend data contract\n- [[wiki/topics/publication-maintenance-moc]] - validation and publication gates\n\n## Agent And Skills\n\n- [[wiki/concepts/agent-skill-governance]] - public-safe skill and rule governance\n- [[wiki/topics/skills-and-tools-moc]] - public skills and tools map\n- [[wiki/topics/ai-agent-systems-moc]] - public agent systems map",
    "pitfalls": [],
    "advancedDirections": [
      {
        "title": "wiki/projects/personal-archive-platform",
        "link": "wiki/projects/personal-archive-platform"
      },
      {
        "title": "wiki/synthesis/archive-information-architecture",
        "link": "wiki/synthesis/archive-information-architecture"
      },
      {
        "title": "wiki/synthesis/personal-archive-public-roadmap",
        "link": "wiki/synthesis/personal-archive-public-roadmap"
      },
      {
        "title": "wiki/synthesis/karpathy-official-wiki-layer",
        "link": "wiki/synthesis/karpathy-official-wiki-layer"
      }
    ],
    "relatedResourceIds": []
  },
  "c_7e9d08f8f6eda5d4": {
    "id": "c_7e9d08f8f6eda5d4",
    "title": "Publication Maintenance MOC",
    "description": "Map for publication gates, privacy scans, manifests, restore evidence, and root maintenance work.",
    "cover": "/path-frontend.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "Publication Maintenance MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Policy",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Validation",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Manifests",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-5",
        "title": "Maintenance",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 5,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "publication",
      "maintenance",
      "privacy",
      "moc"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12",
    "longDescription": "# Publication Maintenance MOC\n\nUse this page before publishing or importing more content.\n\n## Policy\n\n- [[wiki/sources-and-data-policy]] - public/private boundary\n- [[wiki/concepts/private-to-public-promotion-pipeline]] - promotion workflow\n- [[wiki/concepts/public-site-data-boundary]] - frontend/backend data boundary\n- [[AGENTS]] - operating rules\n- [[CLAUDE]] - schema and page format\n\n## Validation\n\n- `python scripts/wiki_check.py .` - structure and wikilink gate\n- `python scripts/privacy_scan.py .` - high-risk privacy gate\n- `python scripts/build_public_inventory.py .` - public inventory refresh\n\n## Manifests\n\n- [raw_sources.csv](../../manifests/raw_sources.csv) - source registry\n- [publication_review.csv](../../manifests/publication_review.csv) - migration/privacy decisions\n- [privacy_scan_report.csv](../../manifests/privacy_scan_report.csv) - privacy scan output\n- [wiki_check_report.json](../../manifests/wiki_check_report.json) - structure check output\n- [restore_drill.csv](../../manifests/restore_drill.csv) - restore rehearsal evidence\n\n## Maintenance\n\n- [[wiki/projects/root-maintenance-backlog]] - current root issues\n- [[log]] - append-only operation log",
    "pitfalls": [],
    "advancedDirections": [
      {
        "title": "wiki/sources-and-data-policy",
        "link": "wiki/sources-and-data-policy"
      },
      {
        "title": "wiki/concepts/private-to-public-promotion-pipeline",
        "link": "wiki/concepts/private-to-public-promotion-pipeline"
      },
      {
        "title": "wiki/concepts/public-site-data-boundary",
        "link": "wiki/concepts/public-site-data-boundary"
      },
      {
        "title": "AGENTS",
        "link": "AGENTS"
      }
    ],
    "relatedResourceIds": []
  },
  "c_68d8f2407d41eb74": {
    "id": "c_68d8f2407d41eb74",
    "title": "Skills and Tools MOC",
    "description": "Map for migrated public-safe skills, tool notes, and reusable operational patterns.",
    "cover": "/path-design.jpg",
    "difficulty": "beginner",
    "estimatedTime": "按主题自定",
    "status": "completed",
    "stages": [
      {
        "id": "step-1",
        "title": "Skills and Tools MOC",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 1,
        "resources": [],
        "status": "available",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-2",
        "title": "Skill Indexes",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 2,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-3",
        "title": "Frequently Used Skills",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 3,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      },
      {
        "id": "step-4",
        "title": "Tooling Areas",
        "description": "从公开 wiki 页面章节生成的路线节点。",
        "order": 4,
        "resources": [],
        "status": "locked",
        "checklist": [
          "读完本节并能连接到相关公开页面。"
        ],
        "deliverable": "读完本节并能连接到相关公开页面。",
        "tips": "按公开资料逐步复刻，不要跳过来源和隐私边界。"
      }
    ],
    "tags": [
      "skills",
      "tools",
      "moc"
    ],
    "whoFor": "希望沿着公开资料路线学习、复刻或维护知识库的读者。",
    "prerequisites": [],
    "outcomes": [
      "形成一条可复用的公开学习或构建路径。"
    ],
    "createdAt": "2026-05-12",
    "updatedAt": "2026-05-12",
    "longDescription": "# Skills and Tools MOC\n\nThis page is the public navigation layer for migrated skill notes.\n\n## Skill Indexes\n\n- [[wiki/concepts/agent-skill-governance]] - current public model for skill governance\n- [[wiki/concepts/04-知识库-领域研究-AI-Agent技术-技能库-MuleRun_Skills_Hub_MOC]] - migrated skill knowledge network\n- [[wiki/concepts/07-技能库-MuleRun_Skills_Hub]] - common source note for migrated skill entries\n- [[wiki/concepts/07-技能库-说明-技能库说明]] - skill-library operating note\n\n## Frequently Used Skills\n\n- [[wiki/concepts/07-技能库-原子技能-browser-use]]\n- [[wiki/concepts/07-技能库-原子技能-doc]]\n- [[wiki/concepts/07-技能库-原子技能-frontend-skill]]\n- [[wiki/concepts/07-技能库-原子技能-gh-address-comments]]\n- [[wiki/concepts/07-技能库-原子技能-gh-fix-ci]]\n- [[wiki/concepts/07-技能库-原子技能-pdf]]\n- [[wiki/concepts/07-技能库-原子技能-screenshot]]\n- [[wiki/concepts/07-技能库-原子技能-security-best-practices]]\n- [[wiki/concepts/07-技能库-原子技能-security-threat-model]]\n\n## Tooling Areas\n\n- [[wiki/topics/03-资源-工具配置-AI工具总览]]\n- [[wiki/topics/04-知识库-07-AI工具演化轨迹]]\n- [[wiki/topics/02-领域-AI工具生态-记忆系统对比]]",
    "pitfalls": [],
    "advancedDirections": [
      {
        "title": "wiki/concepts/agent-skill-governance",
        "link": "wiki/concepts/agent-skill-governance"
      },
      {
        "title": "wiki/concepts/04-知识库-领域研究-AI-Agent技术-技能库-MuleRun_Skills_Hub_MOC",
        "link": "wiki/concepts/04-知识库-领域研究-AI-Agent技术-技能库-MuleRun_Skills_Hub_MOC"
      },
      {
        "title": "wiki/concepts/07-技能库-MuleRun_Skills_Hub",
        "link": "wiki/concepts/07-技能库-MuleRun_Skills_Hub"
      },
      {
        "title": "wiki/concepts/07-技能库-说明-技能库说明",
        "link": "wiki/concepts/07-技能库-说明-技能库说明"
      }
    ],
    "relatedResourceIds": []
  }
};

export const works: Work[] = [
  {
    "id": "c_ac08a639fed4d6c8",
    "title": "Personal Archive Platform",
    "description": "A public-safe project page for the personal archive platform that connects the Obsidian wiki layer to future website data.",
    "cover": "/work-portfolio.jpg",
    "techStack": [
      "archive",
      "llm-wiki",
      "project",
      "showcase",
      "beginner-friendly"
    ],
    "status": "archived",
    "link": "/content/wiki-projects-personal-archive-platform",
    "github": "",
    "duration": "持续迭代",
    "teamSize": "个人主导",
    "challenges": "publishing raw notes；treating private review pages as public sources；letting frontend read the vault directly",
    "learnings": "compiled pages beat raw dumps；public data needs a narrow contract；promotion should be reviewable",
    "relatedPathIds": [],
    "relatedJournalIds": [],
    "createdAt": "2026-05-13",
    "updatedAt": "2026-05-13"
  }
];

export const feedItems: FeedItem[] = [];

export const journalEntries: JournalEntry[] = [];

export const timelineEvents: TimelineEvent[] = [
  {
    "id": "timeline-c_32c45035f9107070",
    "date": "2026-05-13",
    "title": "Agent Skill Governance",
    "description": "A public-safe model for preserving agent and skill knowledge without exposing local prompts or private runtime state.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_32c45035f9107070"
    ],
    "achievements": [],
    "reflection": "A public-safe model for preserving agent and skill knowledge without exposing local prompts or private runtime state.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_8008030b505902e0",
    "date": "2026-05-13",
    "title": "Private To Public Promotion Pipeline",
    "description": "The workflow for rewriting local-only archive material into public-safe wiki pages.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_8008030b505902e0"
    ],
    "achievements": [],
    "reflection": "The workflow for rewriting local-only archive material into public-safe wiki pages.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_151dd4949baa1108",
    "date": "2026-05-13",
    "title": "Public Site Data Boundary",
    "description": "The architecture boundary that keeps the website consuming curated public JSON instead of raw Obsidian content.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_151dd4949baa1108"
    ],
    "achievements": [],
    "reflection": "The architecture boundary that keeps the website consuming curated public JSON instead of raw Obsidian content.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_ac08a639fed4d6c8",
    "date": "2026-05-13",
    "title": "Personal Archive Platform",
    "description": "A public-safe project page for the personal archive platform that connects the Obsidian wiki layer to future website data.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_ac08a639fed4d6c8"
    ],
    "achievements": [],
    "reflection": "A public-safe project page for the personal archive platform that connects the Obsidian wiki layer to future website data.",
    "stage": "works",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_58d7fda66c48c030",
    "date": "2026-05-13",
    "title": "Local Private Compile 2026-05-13",
    "description": "Public-safe source record for the local-only private compile pass that informed the next public wiki pages.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_58d7fda66c48c030"
    ],
    "achievements": [],
    "reflection": "Public-safe source record for the local-only private compile pass that informed the next public wiki pages.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_910d420ab933c045",
    "date": "2026-05-13",
    "title": "Archive Information Architecture",
    "description": "The public information backbone for organizing projects, capabilities, timeline, and review queues before final showcase pages.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_910d420ab933c045"
    ],
    "achievements": [],
    "reflection": "The public information backbone for organizing projects, capabilities, timeline, and review queues before final showcase pages.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_40e886748f617bef",
    "date": "2026-05-13",
    "title": "Capability Evidence Matrix",
    "description": "Public-safe matrix linking capabilities to project evidence, repeatable workflows, and future wiki pages.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_40e886748f617bef"
    ],
    "achievements": [],
    "reflection": "Public-safe matrix linking capabilities to project evidence, repeatable workflows, and future wiki pages.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_d2558f33511a9ddd",
    "date": "2026-05-13",
    "title": "Information Review Queue",
    "description": "Public-safe review queue for unresolved information decisions before more archive content is promoted.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_d2558f33511a9ddd"
    ],
    "achievements": [],
    "reflection": "Public-safe review queue for unresolved information decisions before more archive content is promoted.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_8a14bcb2a5e3fd90",
    "date": "2026-05-13",
    "title": "Personal Archive Public Roadmap",
    "description": "A staged roadmap for growing the public personal archive from safe architecture pages into project and capability pages.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_8a14bcb2a5e3fd90"
    ],
    "achievements": [],
    "reflection": "A staged roadmap for growing the public personal archive from safe architecture pages into project and capability pages.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_43043860b6d67e12",
    "date": "2026-05-13",
    "title": "Project Evidence Matrix",
    "description": "Public-safe matrix of project themes, evidence strength, privacy risk, and next promotion action.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_43043860b6d67e12"
    ],
    "achievements": [],
    "reflection": "Public-safe matrix of project themes, evidence strength, privacy risk, and next promotion action.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_4ffbf9e307e04258",
    "date": "2026-05-13",
    "title": "Public Growth Timeline Framework",
    "description": "A framework for turning private timeline evidence into public milestones without exposing sensitive personal material.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_4ffbf9e307e04258"
    ],
    "achievements": [],
    "reflection": "A framework for turning private timeline evidence into public milestones without exposing sensitive personal material.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_74981be21c4f4c9f",
    "date": "2026-05-13",
    "title": "Personal Archive MOC",
    "description": "Map of the public personal archive platform, promotion workflow, frontend data boundary, and publication roadmap.",
    "category": "milestone",
    "importance": "major",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_74981be21c4f4c9f"
    ],
    "achievements": [],
    "reflection": "Map of the public personal archive platform, promotion workflow, frontend data boundary, and publication roadmap.",
    "stage": "paths",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_b335630551682c19",
    "date": "2026-05-12",
    "title": "An LLM Wiki",
    "description": "A public, privacy-filtered Obsidian LLM Wiki rebuilt around Karpathy's llm-wiki pattern.",
    "category": "milestone",
    "importance": "major",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_b335630551682c19"
    ],
    "achievements": [],
    "reflection": "A public, privacy-filtered Obsidian LLM Wiki rebuilt around Karpathy's llm-wiki pattern.",
    "stage": "paths",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_a48746cae70c44e7",
    "date": "2026-05-12",
    "title": "An LLM Wiki Index",
    "description": "Root navigation page for the public-safe Obsidian LLM Wiki.",
    "category": "milestone",
    "importance": "major",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_a48746cae70c44e7"
    ],
    "achievements": [],
    "reflection": "Root navigation page for the public-safe Obsidian LLM Wiki.",
    "stage": "paths",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_0b2b8021fc47d672",
    "date": "2026-05-12",
    "title": "LLM Wiki Index",
    "description": "Short workbench for the rebuilt public-safe LLM Wiki.",
    "category": "milestone",
    "importance": "major",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_0b2b8021fc47d672"
    ],
    "achievements": [],
    "reflection": "Short workbench for the rebuilt public-safe LLM Wiki.",
    "stage": "paths",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_ad9a9fc54757ca67",
    "date": "2026-05-12",
    "title": "Sources and Data Policy",
    "description": "Source, privacy, and publication rules for this public-safe wiki.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_ad9a9fc54757ca67"
    ],
    "achievements": [],
    "reflection": "Source, privacy, and publication rules for this public-safe wiki.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_34b380dfec2c06c0",
    "date": "2026-05-12",
    "title": "GitHub Reference Projects",
    "description": "Secondary engineering references for local-first LLM Wiki implementations.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_34b380dfec2c06c0"
    ],
    "achievements": [],
    "reflection": "Secondary engineering references for local-first LLM Wiki implementations.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_08b81444115464f6",
    "date": "2026-05-12",
    "title": "Karpathy LLM Wiki Pattern",
    "description": "Official pattern source for this vault architecture.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_08b81444115464f6"
    ],
    "achievements": [],
    "reflection": "Official pattern source for this vault architecture.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_d1f1b66d423fc694",
    "date": "2026-05-12",
    "title": "llm-wikid",
    "description": "Secondary GitHub reference for Obsidian vault template and wiki maintenance conventions.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_d1f1b66d423fc694"
    ],
    "achievements": [],
    "reflection": "Secondary GitHub reference for Obsidian vault template and wiki maintenance conventions.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_55208509a7f3108b",
    "date": "2026-05-12",
    "title": "obsidian-llm-wiki-local",
    "description": "Secondary GitHub reference for local-first LLM Wiki implementation ideas.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_55208509a7f3108b"
    ],
    "achievements": [],
    "reflection": "Secondary GitHub reference for local-first LLM Wiki implementation ideas.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_e408088da7f9f832",
    "date": "2026-05-12",
    "title": "Pre-Rebuild Vault Archive",
    "description": "Local private archive used as the source for public-safe migration.",
    "category": "milestone",
    "importance": "normal",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_e408088da7f9f832"
    ],
    "achievements": [],
    "reflection": "Local private archive used as the source for public-safe migration.",
    "stage": "library",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_3d19f3d825d4e136",
    "date": "2026-05-12",
    "title": "AI Agent Systems MOC",
    "description": "Map for public-safe AI agent framework and architecture notes migrated into the wiki.",
    "category": "milestone",
    "importance": "major",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_3d19f3d825d4e136"
    ],
    "achievements": [],
    "reflection": "Map for public-safe AI agent framework and architecture notes migrated into the wiki.",
    "stage": "paths",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_87e2a1ac5dbe8a31",
    "date": "2026-05-12",
    "title": "LLM Wiki MOC",
    "description": "Map for the vault architecture, schema, source policy, and rebuild alignment notes.",
    "category": "milestone",
    "importance": "major",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_87e2a1ac5dbe8a31"
    ],
    "achievements": [],
    "reflection": "Map for the vault architecture, schema, source policy, and rebuild alignment notes.",
    "stage": "paths",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_7e9d08f8f6eda5d4",
    "date": "2026-05-12",
    "title": "Publication Maintenance MOC",
    "description": "Map for publication gates, privacy scans, manifests, restore evidence, and root maintenance work.",
    "category": "milestone",
    "importance": "major",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_7e9d08f8f6eda5d4"
    ],
    "achievements": [],
    "reflection": "Map for publication gates, privacy scans, manifests, restore evidence, and root maintenance work.",
    "stage": "paths",
    "relatedPathIds": []
  },
  {
    "id": "timeline-c_68d8f2407d41eb74",
    "date": "2026-05-12",
    "title": "Skills and Tools MOC",
    "description": "Map for migrated public-safe skills, tool notes, and reusable operational patterns.",
    "category": "milestone",
    "importance": "major",
    "cover": "/hero-cover.jpg",
    "relatedLinks": [
      "/content/c_68d8f2407d41eb74"
    ],
    "achievements": [],
    "reflection": "Map for migrated public-safe skills, tool notes, and reusable operational patterns.",
    "stage": "paths",
    "relatedPathIds": []
  }
];
